sudo: false
language: python
python:
  - '2.7'
  - '3.4'
install:
  - if [ -s "requirements.txt" ]; then pip install -r requirements.txt; fi;
  - python setup.py develop
script: python -m unittest discover
